package com.localvault.app.ui.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Button
import androidx.compose.material3.CenterAlignedTopAppBar
import androidx.compose.material3.ElevatedCard
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Slider
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.localvault.app.R
import com.localvault.app.security.PasswordTools
import com.localvault.app.ui.components.PasswordStrengthBar
import com.localvault.app.util.copyToClipboardWithTimeout

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GeneratorScreen(
    onUsePassword: ((String) -> Unit)? = null,
) {
    val context = LocalContext.current
    var length by remember { mutableFloatStateOf(18f) }
    var includeNumbers by remember { mutableStateOf(true) }
    var includeSymbols by remember { mutableStateOf(true) }
    var generated by remember {
        mutableStateOf(
            PasswordTools.generate(
                length = length.toInt(),
                useSymbols = includeSymbols,
                useNumbers = includeNumbers,
            ),
        )
    }

    fun regenerate() {
        generated = PasswordTools.generate(
            length = length.toInt(),
            useSymbols = includeSymbols,
            useNumbers = includeNumbers,
        )
    }

    Scaffold(
        topBar = {
            CenterAlignedTopAppBar(
                title = { Text(stringResource(R.string.generator)) },
                actions = {
                    IconButton(onClick = { regenerate() }) {
                        Icon(Icons.Default.Refresh, contentDescription = stringResource(R.string.generate_password))
                    }
                },
            )
        },
        containerColor = MaterialTheme.colorScheme.background,
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(20.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(18.dp),
        ) {
            ElevatedCard(modifier = Modifier.fillMaxWidth()) {
                Column(
                    modifier = Modifier.padding(18.dp),
                    verticalArrangement = Arrangement.spacedBy(14.dp),
                ) {
                    Text(
                        stringResource(R.string.generated_password),
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.68f),
                    )
                    Text(
                        generated,
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.SemiBold,
                    )
                    PasswordStrengthBar(strength = PasswordTools.strength(generated))
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        Button(onClick = { regenerate() }) {
                            Icon(Icons.Default.Refresh, contentDescription = null)
                            Text(stringResource(R.string.generate_password), modifier = Modifier.padding(start = 8.dp))
                        }
                        IconButton(
                            onClick = {
                                copyToClipboardWithTimeout(
                                    context,
                                    "generated password",
                                    generated,
                                )
                            },
                        ) {
                            Icon(Icons.Default.ContentCopy, contentDescription = stringResource(R.string.copy_generated_password))
                        }
                    }
                    if (onUsePassword != null) {
                        Button(
                            onClick = { onUsePassword(generated) },
                            modifier = Modifier.fillMaxWidth(),
                        ) {
                            Text(stringResource(R.string.use_generated_password))
                        }
                    }
                }
            }

            ElevatedCard(modifier = Modifier.fillMaxWidth()) {
                Column(
                    modifier = Modifier.padding(18.dp),
                    verticalArrangement = Arrangement.spacedBy(16.dp),
                ) {
                    Text(
                        "${stringResource(R.string.password_length)}: ${length.toInt()}",
                        style = MaterialTheme.typography.titleMedium,
                    )
                    Slider(
                        value = length,
                        onValueChange = {
                            length = it
                            regenerate()
                        },
                        valueRange = 8f..32f,
                        steps = 23,
                    )
                    GeneratorSwitch(
                        label = stringResource(R.string.include_numbers),
                        checked = includeNumbers,
                        onCheckedChange = {
                            includeNumbers = it
                            regenerate()
                        },
                    )
                    GeneratorSwitch(
                        label = stringResource(R.string.include_symbols),
                        checked = includeSymbols,
                        onCheckedChange = {
                            includeSymbols = it
                            regenerate()
                        },
                    )
                }
            }
        }
    }
}

@Composable
private fun GeneratorSwitch(
    label: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(label, style = MaterialTheme.typography.bodyLarge)
        Switch(checked = checked, onCheckedChange = onCheckedChange)
    }
}
